# Generated by Django 5.0.3 on 2024-03-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], default='Pria', max_length=10)),
                ('kategori_dituju', models.CharField(choices=[('Kepala Sekolah', 'Kepala Sekolah'), ('Guru', 'Guru'), ('TU', 'TU'), ('Siswa', 'Siswa')], default='Siswa', max_length=20)),
                ('pihak_dituju', models.CharField(max_length=100)),
                ('keperluan', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=34)),
                ('foto', models.ImageField(default=False, null=True, upload_to='')),
            ],
            options={
                'db_table': 'guest',
            },
        ),
    ]
